### PR TITLE
fix(store): bybit balances

### PR DESCRIPTION
**Pull request by neeeekitos**
Check monorepo's PR description

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Testing it rn

**Comment by NeOMakinG** [comment]
Managed to add a bybit accounts, balances a fetched. trading is working and  ✅ 

image
image
image

Couldn't test a withdraw as we don't have enough funds but as nothing changed on CCXT side, should work as expected

**Comment by NeOMakinG** [comment]
@neeeekitos could you bump the package.json version before merging?

**Comment by neeeekitos** [comment]
Sure ser

**Pull request merged**
